### ISSUE TITLE
ext.php should be more verbose

### ISSUE THREAD

**Issue by 3D-I** [javiexin/extdepend#4]
I guess I found a solution for using a more verbose/customisable output in ext.php.
At least with 3.2.0, using the new language object.

**Comment by javiexin** [comment]
What do you mean, the Dependency Mgr ext.php, or the "subordinate" extensions ext.php files?
For the former, let me know what you want, I am all for it. I think I know how to include language there, but I'll ask if I have issues.
For the latter, no: it is on purpose, I want it to be the minimum effort for extension authors to modify their extensions for this.  If we were to give that extra verbosity in all extensions, then we would require also a language file change, and would be more complicated overall.  But, let's discuss it anyhow!

**Comment by 3D-I** [comment]
In effect I am speaking about the subordinates, and yes.. needs a study.
At the end of all: if the author let's say doesn't want to add an extra bit for this it's up to him, if that bit extra is missin there we should provide a default.. something the like: "no info provided".

**Comment by javiexin** [comment]
Take into consideration that the is_enableable method is only used/needed when this is not installed... So nothing we can do about it... We can propose a more complex code for it, with language and all, but in the end it will be entirely up to the extension author. We cannot provide any default if the DepMgr is not installed... And if it is installed, this is not needed, as it is already covered...

**Comment by javiexin** [comment]
Added explanation in README.md, sample language file, and full example in exttestchild5.

**Comment by 3D-I** [comment]
That's exactly what I meant, good. This commit is for the 3.1.x/3.2.x BC's sake.


The same concept applies to 3.2.x using the language object instead.

```
public function is_enableable()
{
    if (!$this->container->get('ext.manager')->is_enabled('javiexin/extdependencies'))
    {
        $this->container->get('language')->add_lang('vendor/extension', 'extdependencies');
        trigger_error($this->container->get('user')->lang['DEPENCY_MANAGER_REQUIRED_NOTICE'], E_USER_WARNING);
    }
    return true;
}
```
